global:
  pattern: rhdh-validated-pattern
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  rhdh:
    admins:
    - handle: butler54
    - handle: derekwaters
    - handle: aspanner
    - handle: caldeirav
    users:
    - none
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
