kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: My zany developer hub
      baseUrl: https://backstage-{{ .Values.instanceName }}-{{ Release.Namespace }}.{{ .Values.global.localClusterDomain }}
    