kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config
data:
  app-config-rhdh.yaml: |
    app:
      title: My zany developer hub
      baseUrl: https://backstage-{{ .Values.instanceName }}-{{ .Release.Namespace }}.{{ .Values.global.localClusterDomain }}
    integrations:
      github:
        - host: github.com
          # Reference here is to the app config secret field name
          token: "${GITHUB_ACCESS_TOKEN}"
    auth:
      allowGuestAccess: ${{ .Values.auth.allowGuestAccess }}
      environment: development
      providers:
        github:
          development:
            clientId: "${GITHUB_CLIENT_ID}"
            clientSecret: "${GITHUB_CLIENT_SECRET}"
    enabled: 
      github: true
    backend:
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"
      baseUrl: https://backstage-{{ .Values.instanceName }}-{{ .Release.Namespace }}.{{ .Values.global.localClusterDomain }}
      cors:
        origin: https://backstage-{{ .Values.instanceName }}-{{ .Release.Namespace }}.{{ .Values.global.localClusterDomain }}
    permission:
      enabled: true
      rbac:
        admin:
          users:
{{- range .Values.global.rhdh.admins -}}

            - name: user:default/{{ .handle }}

{{- end -}}
