---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: app-config-eso
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: app-config-rhdh-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.appConfigSecret.key }}