apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: {{ .Values.instanceName }}
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: app-config
         - name: rbac-config
    dynamicPluginsConfigMapName: dynamic-plugins
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policy
    extraEnvs:
      secrets:
        - name: app-config-rhdh-secret
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true