apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: {{ .Values.instanceName }}
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: app-config-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
