kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-config
data:
  rhdh-config-rbac.yaml: |
    permission:
      enabled: true
      rbac:
        policies-csv-file: ./rbac-policy.csv
        admin:
          users:
{{- range .Values.global.rhdh.admins -}}
            - name: user:default/{{ .handle }} 

{{- end -}}