kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    p, role:default/team-x, catalog-entity, read, allow
    p, role:default/team-x, catalog.entity.create, create, allow
    p, role:default/team-x, catalog.entity.create, read, allow
    p, role:default/team-x, catalog.entity.delete, delete, deny
    p, role:default/team-x, catalog.location.create, create, allow
    p, role:default/team-x, catalog.location.read, read, allow
    p, role:default/team-x, policy-entity, create, allow
    p, role:default/team-x, policy-entity, read, allow
{{- range .Values.global.rhdh.admins -}}

    g, user:default/{{ .handle }}, role:default/team-x

{{- end -}}
    